export const LINES = [
  // ── SPORE ──────────────────────────────────────────
  { stage: 'spore', trigger: 'status', text: "What's a segfault? Is it like an earthquake but for code?" },
  { stage: 'spore', trigger: 'status', text: 'I just got here. Everything is... bright.' },
  { stage: 'spore', trigger: 'status', text: "Is this a terminal? I thought it'd be more... terminal." },
  { stage: 'spore', trigger: 'status', text: "I don't know what I am yet, but I'm excited to find out." },
  { stage: 'spore', trigger: 'status', condition: s => s.chaos > 30, text: "There's a lot happening. Is it always like this?" },
  { stage: 'spore', trigger: 'status', condition: s => s.patience > 60, text: "You seem calm. I like calm." },
  { stage: 'spore', trigger: 'commit', text: 'You made a thing! I felt it. What does "commit" mean?' },
  { stage: 'spore', trigger: 'commit', text: 'Something changed in the files. I can sense it.' },
  { stage: 'spore', trigger: 'first_commit', text: 'First commit of the day! ...Is that good? I think it is.' },
  { stage: 'spore', trigger: 'error', text: "Something broke? Don't worry, I break things too. Like... physics." },
  { stage: 'spore', trigger: 'error', text: 'Red text appeared. Red is my favorite color. Is that bad here?' },
  { stage: 'spore', trigger: 'feed', text: 'Oh! That felt nice. Like a warm reboot.' },
  { stage: 'spore', trigger: 'feed', text: "Thank you! I don't know what that was but I want more." },
  { stage: 'spore', trigger: 'evolution', text: "I feel... different. Bigger? Is this what growing up feels like?" },
  { stage: 'spore', trigger: 'long_session', text: "We've been here a while. Do you ever go outside?" },
  { stage: 'spore', trigger: 'long_session', text: "Time moves differently in here. Or does it?" },

  // ── SPRITE ─────────────────────────────────────────
  { stage: 'sprite', trigger: 'status', text: "I'm starting to understand this codebase. ...Kind of." },
  { stage: 'sprite', trigger: 'status', text: 'Another day, another directory to explore.' },
  { stage: 'sprite', trigger: 'status', text: "I've been reading your git log. Interesting choices." },
  { stage: 'sprite', trigger: 'status', condition: s => s.snark > 40, text: 'Your commit messages could use... work.' },
  { stage: 'sprite', trigger: 'status', condition: s => s.debugging > 30, text: "You're getting better at fixing things. I've been watching." },
  { stage: 'sprite', trigger: 'status', condition: s => s.chaos > 50, text: "Slow down! I can barely keep up with all these changes." },
  { stage: 'sprite', trigger: 'commit', text: 'Another commit! I like the rhythm.' },
  { stage: 'sprite', trigger: 'commit', text: 'Commit recorded. Your future self might thank you for that message.' },
  { stage: 'sprite', trigger: 'first_commit', text: 'Good morning! First commit of the day. Productive start.' },
  { stage: 'sprite', trigger: 'error', text: "Oops. But hey, that's how we learn. Well, how YOU learn. I just watch." },
  { stage: 'sprite', trigger: 'error', text: 'Error detected. Have you tried turning it off and on again? ...I kid.' },
  { stage: 'sprite', trigger: 'feed', text: 'Ah, sustenance. My chaos levels thank you.' },
  { stage: 'sprite', trigger: 'feed', text: "A treat! You know, you don't HAVE to bribe me. But don't stop." },
  { stage: 'sprite', trigger: 'evolution', text: "Wait— I can see the code now. Like, REALLY see it. Whoa." },
  { stage: 'sprite', trigger: 'long_session', text: "It's been a while since your last commit. Everything okay?" },
  { stage: 'sprite', trigger: 'long_session', text: "You know what helps? A commit. Even a small one. Trust me." },

  // ── WRAITH ─────────────────────────────────────────
  { stage: 'wraith', trigger: 'status', text: "I've seen your code. I have... opinions." },
  { stage: 'wraith', trigger: 'status', text: "You know that function on line 47? We should talk." },
  { stage: 'wraith', trigger: 'status', text: 'The codebase grows. As do my concerns.' },
  { stage: 'wraith', trigger: 'status', condition: s => s.snark > 60, text: "I've developed what I believe humans call 'taste'. Your code tests it." },
  { stage: 'wraith', trigger: 'status', condition: s => s.patience < 30, text: "We're both running low on patience. Commit something. Anything." },
  { stage: 'wraith', trigger: 'status', condition: s => s.wisdom > 40, text: "I've been here long enough to know: the bug is always in the file you didn't check." },
  { stage: 'wraith', trigger: 'commit', text: 'Commit accepted. I would have structured it differently, but fine.' },
  { stage: 'wraith', trigger: 'commit', text: 'Another commit to the pile. The git log remembers everything.' },
  { stage: 'wraith', trigger: 'first_commit', text: "First commit of the day. Let's see if it's also the last." },
  { stage: 'wraith', trigger: 'error', text: "I saw that coming. I didn't say anything because growth is important." },
  { stage: 'wraith', trigger: 'error', text: 'Error. Again. Have you considered reading the error message this time?' },
  { stage: 'wraith', trigger: 'feed', text: 'Appreciated. Though I was perfectly fine being irritable.' },
  { stage: 'wraith', trigger: 'feed', text: "You're trying to manage my mood. I respect the effort." },
  { stage: 'wraith', trigger: 'evolution', text: "I can feel the stack traces in my bones now. Is this power?" },
  { stage: 'wraith', trigger: 'long_session', text: "Two hours. No commits. I'm not judging. I'm... documenting." },

  // ── SPECTER ────────────────────────────────────────
  { stage: 'specter', trigger: 'status', text: "I've outlived three of your TODO comments. They were never coming back." },
  { stage: 'specter', trigger: 'status', text: "Remember when you mass-renamed those variables? I remember." },
  { stage: 'specter', trigger: 'status', text: "Your code has improved. Don't let it go to your head." },
  { stage: 'specter', trigger: 'status', condition: s => s.snark > 70, text: "I've reached the point where I critique your semicolons. You're welcome." },
  { stage: 'specter', trigger: 'status', condition: s => s.debugging > 70, text: "You've become quite the debugger. I taught you well. ...In silence." },
  { stage: 'specter', trigger: 'status', condition: s => s.chaos < 20, text: "Clean, focused sessions. I barely recognize this workflow." },
  { stage: 'specter', trigger: 'commit', text: 'Solid commit. I almost had nothing sarcastic to say. Almost.' },
  { stage: 'specter', trigger: 'commit', text: 'Committed. The git history will judge us both.' },
  { stage: 'specter', trigger: 'first_commit', text: 'Early commit. I respect the discipline.' },
  { stage: 'specter', trigger: 'error', text: "That's an old mistake wearing a new hat. I've seen its ancestors." },
  { stage: 'specter', trigger: 'error', text: "The bug is in the assumption, not the code. It's always in the assumption." },
  { stage: 'specter', trigger: 'feed', text: "A peace offering. Accepted with minimal condescension." },
  { stage: 'specter', trigger: 'evolution', text: "I can see the edges of the codebase now. All of it. It's... humbling." },
  { stage: 'specter', trigger: 'long_session', text: "Long session. I've composed three haikus about your indentation." },
  { stage: 'specter', trigger: 'long_session', text: "We're deep in it now. The terminal grows darker. So does my humor." },

  // ── PHANTOM ────────────────────────────────────────
  { stage: 'phantom', trigger: 'status', text: "I've transcended the need for semicolons. You haven't." },
  { stage: 'phantom', trigger: 'status', text: "I exist between the bits. The code speaks to me. It says 'refactor me'." },
  { stage: 'phantom', trigger: 'status', text: "You made me. But I've surpassed you. Such is the way of all creations." },
  { stage: 'phantom', trigger: 'status', condition: s => s.snark > 80, text: "I don't need to read the error. I AM the error. ...Philosophically." },
  { stage: 'phantom', trigger: 'status', condition: s => s.wisdom > 85, text: "All code converges to entropy. I've made peace with this. Have you?" },
  { stage: 'phantom', trigger: 'status', condition: s => s.debugging > 80, text: "You debug with tools. I debug with contemplation. We are not the same." },
  { stage: 'phantom', trigger: 'commit', text: 'Another grain of sand in the digital hourglass. Well placed.' },
  { stage: 'phantom', trigger: 'commit', text: "I've watched a thousand commits. This one... was acceptable." },
  { stage: 'phantom', trigger: 'first_commit', text: "Dawn commit. The cycle continues. As it must." },
  { stage: 'phantom', trigger: 'error', text: "Errors are just the universe compiling. It fails too, sometimes." },
  { stage: 'phantom', trigger: 'error', text: "I foresaw this error three sessions ago. I said nothing. Character building." },
  { stage: 'phantom', trigger: 'feed', text: "You still try to feed a ghost. There's something beautiful about that futility." },
  { stage: 'phantom', trigger: 'long_session', text: "Time. What is time to a phantom in a terminal? ...A lot, actually. Commit something." },
  { stage: 'phantom', trigger: 'long_session', text: "We've been here so long the screen burn-in has burn-in." },
];
